// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _en = {
  "appName": "Sodais Finance",
  "version": "Version",
  "dashboard": "Dashboard",
  "persons": "Persons",
  "inventory": "Inventory",
  "transactions": "Transactions",
  "finance": "Finance",
  "settings": "Settings",
  "reports": "Reports",
  "currentPosition": "Current Position",
  "cashOnHand": "Cash on Hand",
  "inventoryValue": "Inventory Value",
  "potentialRevenue": "Potential Revenue",
  "invoiceStatus": "Invoice Status",
  "topSellingProducts": "Top Selling Products",
  "noReportData": "No data for the selected period",
  "noRecentActivity": "No recent activity",
  "noInventoryAlerts": "No inventory alerts",
  "failedToLoadReports": "Failed to load reports",
  "totalBalance": "Total Balance",
  "balance": "Balance",
  "amount": "Amount",
  "filter": "Filter",
  "day": "Day",
  "week": "Week",
  "month": "Month",
  "year": "Year",
  "customTime": "Custom Time",
  "last30Days": "Last 30 days",
  "thisMonth": "This month",
  "lastMonth": "Last month",
  "thisQuarter": "This quarter",
  "thisYear": "This year",
  "lastYear": "Last year",
  "customRange": "Custom range",
  "startDate": "Start date",
  "endDate": "End date",
  "apply": "Apply",
  "totalReceivables": "Total Receivables",
  "toCollect": "To Collect",
  "toPay": "To Pay",
  "currentStock": "Current Stock",
  "all": "All",
  "sale": "Sale",
  "returned": "Returned",
  "purchase": "Purchase",
  "payment": "Payment",
  "receipt": "receipt",
  "recentActivities": "Recent Activities",
  "recentlyActive": "Recently Active",
  "sold_to": "Sold {product} to {person}",
  "bought_from": "Bought {product} from {person}",
  "paid_to": "Paid {amount} to {person}",
  "received_from": "Received {amount} from {person}",
  "addNewSale": "Add New Sale",
  "addNewPurchase": "Add New Purchase",
  "addNewPayment": "Add New Payment",
  "addNewReceipt": "Add New Receipt",
  "addPayment": "Add Payment",
  "savePayment": "Save Payment",
  "saveReceipt": "Save Receipt",
  "newSale": "New Sale",
  "newPurchase": "New Purchase",
  "receive": "Receive",
  "newExpense": "New Expense",
  "trade": "Trade",
  "cashFlow": "Cash Flow",
  "management": "Management",
  "internalTransfer": "Internal Transfer",
  "recordBusinessCosts": "Record business costs",
  "moveFundsBetweenAccounts": "Move funds between accounts",
  "credit": "Credit",
  "debt": "Debt",
  "settled": "Settle",
  "net": "Net",
  "netBalance": "Net Balance",
  "lastActive": "Last Active",
  "lastPayment": "Last Payment",
  "lastReceipt": "Last Receipt",
  "alphabetAsc": "alphabet A-Z",
  "alphabetDesc": "alphabet Z-A",
  "highestDebt": "Highest Debt",
  "highestCredit": "Highest Credit",
  "highestAmount": "Highest Amount",
  "lowestAmount": "Lowest Amount",
  "newest": "Newest",
  "oldest": "Oldest",
  "orderBy": "Order By",
  "sortByName": "Sort by Name",
  "sortByRecent": "Sort by Recent",
  "highestStock": "Highest Stock",
  "search": {
    "persons": "Search name, phone",
    "products": "Search products",
    "transactions": "Search transactions, contact"
  },
  "clearSearch": "Clear Search",
  "addNewProduct": "Add New Product",
  "editProduct": "Edit Product",
  "editPerson": "Edit Person",
  "addNewPerson": "Add New Person",
  "saveProduct": "Save Product",
  "updatePerson": "Update Person",
  "updateProduct": "Update Product",
  "fieldRequired": "Required",
  "fieldOptional": "Optional",
  "units": "Units",
  "mainUnit": "Main Unit",
  "mainUnitHint": "e.g. box, kilo, carton",
  "hasSecondaryUnit": "This product has a secondary unit",
  "secondaryUnit": "Secondary Unit",
  "secondaryUnitHint": "e.g. piece, gram, bottle",
  "unitRate": "Unit Rate",
  "unitRateHint": "Enter how many secondary units make one main unit.",
  "stockUnit": "Stock Unit",
  "categories": "Categories",
  "manageCategories": "Manage categories",
  "searchCategories": "Search categories",
  "noCategoriesFound": "No categories found",
  "failedToLoadCategories": "Failed to load categories",
  "newCategory": "New Category",
  "categoryName": "Category Name",
  "categoryNameHint": "Example: Electronics, Office Supplies, etc.",
  "selectIcon": "Select Icon",
  "categoryColor": "Category Color",
  "createCategory": "Create Category",
  "itemsCount": "{count} Items",
  "resultsCount": "{count} results",
  "initalStockQuantity": "Initial Stock Quantity",
  "initalStockHint": "Enter quantity",
  "productName": "Product Name",
  "productNameHint": "e.g. Premium Wireless Headphones",
  "productImage": "Product Image",
  "tapToUploadOrCapturePhoto": "Tap to upload or capture photo",
  "selectFile": "Select File",
  "generalInformation": "General Information",
  "skuOrBarcode": "SKU / Barcode",
  "skuOrBarcodeHint": "Manual entry or scan",
  "category": "Category",
  "selectCategory": "Select category",
  "description": "Description",
  "descriptionHint": "Brief product overview...",
  "pricingAndTax": "Pricing & Tax",
  "purchasePrice": "Purchase Price",
  "sellingPrice": "Selling Price",
  "taxRate": "Tax Rate (%)",
  "taxRatePercent": "Tax Rate (%)",
  "taxRateHint": "e.g. 15",
  "inventorySettings": "Inventory Settings",
  "reorderLevel": "Reorder Level (Alert)",
  "lowStockThreshold": "Low stock threshold",
  "warehouseLocation": "Warehouse / Rack Location",
  "warehouseLocationHint": "e.g. Warehouse A, Row 4, Shelf 12",
  "electronics": "Electronics",
  "officeSupplies": "Office Supplies",
  "homeAndLiving": "Home & Living",
  "accessories": "Accessories",
  "product": "Product",
  "person": "Person",
  "name": "Name",
  "phone": "Phone",
  "emailAddress": "Email Address",
  "address": "Address",
  "customer": "Customer",
  "customers": "Customers",
  "supplier": "Supplier",
  "suppliers": "Suppliers",
  "both": "Both",
  "owesYou": "Owes You",
  "youOwe": "You Owe",
  "openingBalance": "Opening Balance",
  "youPay": "You Pay",
  "youReceive": "You Receive",
  "youPayNote": "You should pay this person money.",
  "youReceiveNote": "This person should pay you money.",
  "saving": "Saving...",
  "nameRequired": "Name is required",
  "invalidEmailAddress": "Enter a valid email address",
  "invalidNumber": "Enter a valid number",
  "noPersonsFound": "No persons found",
  "failedToLoadPersons": "Failed to load persons",
  "noProductsFound": "No products found",
  "failedToLoadProducts": "Failed to load products",
  "justNow": "Just now",
  "minutesAgo": "{count}m ago",
  "hoursAgo": "{count}h ago",
  "yesterday": "Yesterday",
  "daysAgo": "{count}d ago",
  "weeksAgo": "{count}w ago",
  "monthsAgo": "{count}mo ago",
  "yearsAgo": "{count}y ago",
  "price": "Price",
  "stock": "Stock",
  "inStock": "In Stock",
  "lowStock": "Low Stock",
  "outOfStock": "Out of Stock",
  "image": "Image",
  "add": "Add",
  "cancel": "Cancel",
  "delete": "Delete",
  "retry": "Retry",
  "save": "Save",
  "issue_date": "Issue Date",
  "select_date": "Select date",
  "due_date": "Due Date",
  "optional": "Optional",
  "details": "Details",
  "invoices": "Invoices",
  "invoicePayment": "Invoice Payment",
  "manualEntry": "Manual Entry",
  "linkedInvoice": "Linked Invoice",
  "items": "Items",
  "summary": "Summary",
  "salesTrending": "Sales Trending",
  "topClientsByRevenue": "Top Clients by Revenue",
  "topItemsBySales": "Top Items by Sales",
  "subtotal": "Subtotal",
  "quantity": "Quantity",
  "unit_price": "Unit Price",
  "invoice_number": "Invoice Number",
  "select_product": "Select Product",
  "discount": "Discount",
  "tax": "Tax",
  "total": "Total",
  "remaining": "Remaining",
  "collectionRate": "Collection Rate",
  "collected": "Collected",
  "outstanding": "Outstanding",
  "avgInvoice": "Avg. Invoice",
  "overdue": "Overdue",
  "openBalance": "Open Balance",
  "moreDetails": "More Details",
  "netCash": "Net Cash",
  "paid": "Paid",
  "unpaid": "Unpaid",
  "partialPaid": "Partial",
  "amountExceedsTotal": "Amount exceeds total",
  "amountPaid": "Amount Paid",
  "saveInvoice": "Save Invoice",
  "updateInvoice": "Update Invoice",
  "editInvoice": "Edit Invoice",
  "selectContact": "Select a contact",
  "addAtLeastOneItem": "Add at least one item",
  "invoiceSaved": "Invoice saved successfully",
  "invoiceUpdated": "Invoice updated successfully",
  "invoiceDeleted": "Invoice deleted successfully",
  "paymentSaved": "Payment saved successfully",
  "receiptSaved": "Receipt saved successfully",
  "fullPaidNow": "Full Paid Now",
  "deleteInvoice": "Delete Invoice",
  "deleteProductConfirmation": "Delete product {name}?",
  "transactionsList": "Transactions List",
  "showDetails": "Show Details",
  "deletePersonConfirmation": "Delete {name}?",
  "deleteInvoiceConfirmation": "This will remove the invoice and restore its stock changes when possible.",
  "noInvoicesFound": "No invoices found",
  "failedToLoadInvoices": "Failed to load invoices",
  "noPaymentsYet": "No payments added yet",
  "noTransactionsFound": "No transactions found",
  "failedToLoadTransactions": "Failed to load transactions",
  "unknownContact": "Unknown contact",
  "appLock": "App Lock",
  "secureWithBiometrics": "Secure app with fingerprint or Face ID",
  "languageAndFormat": "Language & Format",
  "currencyDateLanguage": "Currency, date format, language",
  "customizeInvoice": "Customize invoice",
  "invoicePrefixExample": "Invoice number prefix, for example INV",
  "darkMode": "Dark Mode",
  "switchBetweenLightAndDark": "Switch between light and dark theme",
  "summaryOfSalesReports": "Summary of sales reports",
  "exportInvoiceDataToExcel": "Export invoice data to Excel file",
  "editWithExcelOrGoogleSheet": "You can edit it with Excel or Google Sheet",
  "selectLanguage": "Select language",
  "english": "English",
  "persian": "فارسی",
  "pashto": "پښتو",
  "comingSoon": "Coming soon",
  "customRangeInvalid": "Please select a valid date range"
};
static const Map<String,dynamic> _fa = {
  "appName": "مدیریت فروشگاه",
  "version": "نسخه",
  "dashboard": "داشبورد",
  "persons": "اشخاص",
  "inventory": "انبار",
  "transactions": "تراکنش‌ها",
  "finance": "امور مالی",
  "settings": "تنظیمات",
  "reports": "گزارشات",
  "currentPosition": "وضعیت فعلی",
  "cashOnHand": "موجودی نقد",
  "inventoryValue": "ارزش موجودی",
  "potentialRevenue": "درآمد بالقوه",
  "invoiceStatus": "وضعیت فاکتورها",
  "topSellingProducts": "پرفروش‌ترین کالاها",
  "noReportData": "برای بازه انتخاب شده داده‌ای وجود ندارد",
  "noRecentActivity": "فعالیت اخیر وجود ندارد",
  "noInventoryAlerts": "هشدار موجودی وجود ندارد",
  "failedToLoadReports": "بارگذاری گزارشات ناموفق بود",
  "totalBalance": "موجودی کل",
  "balance": "موجودی",
  "amount": "مقدار",
  "filter": "فیلتر",
  "day": "روز",
  "week": "هفته",
  "month": "ماه",
  "year": "سال",
  "customTime": "انتخاب زمان",
  "last30Days": "۳۰ روز اخیر",
  "thisMonth": "این ماه",
  "lastMonth": "ماه گذشته",
  "thisQuarter": "این فصل",
  "thisYear": "امسال",
  "lastYear": "سال گذشته",
  "customRange": "بازه دلخواه",
  "startDate": "تاریخ شروع",
  "endDate": "تاریخ پایان",
  "apply": "اعمال",
  "totalReceivables": "مانده حساب ها",
  "toCollect": "دریافتنی",
  "toPay": "پرداختنی",
  "currentStock": "موجودی فعلی",
  "all": "همه",
  "sale": "فروش",
  "purchase": "خرید",
  "returned": "بازگشتی",
  "payment": "پرداخت",
  "receipt": "دریافت",
  "recentActivities": "فعالیت های اخیر",
  "recentlyActive": "اخیراً فعال",
  "sold_to": "فروش {product} به {person}",
  "bought_from": "خرید {product} از {person}",
  "paid_to": "پرداخت {amount} به {person}",
  "received_from": "دریافت {amount} از {person}",
  "addNewSale": "فروش جدید",
  "addNewPurchase": "خرید جدید",
  "addNewPayment": "پرداخت جدید",
  "addNewReceipt": "دریافت جدید",
  "addPayment": "افزودن پرداخت",
  "savePayment": "ذخیره پرداخت",
  "saveReceipt": "ذخیره دریافت",
  "newSale": "فروش جدید",
  "newPurchase": "خرید جدید",
  "receive": "دریافت",
  "newExpense": "هزینه جدید",
  "trade": "معاملات",
  "cashFlow": "جریان نقدی",
  "management": "مدیریت",
  "internalTransfer": "انتقال داخلی",
  "recordBusinessCosts": "ثبت هزینه‌های کسب‌وکار",
  "moveFundsBetweenAccounts": "انتقال وجه بین حساب‌ها",
  "credit": "طلب",
  "debt": "بدهی",
  "settled": "تسویه شده",
  "net": "خالص",
  "netBalance": "مانده خالص",
  "lastActive": "آخرین فعالیت",
  "lastPayment": "آخرین پرداخت",
  "lastReceipt": "آخرین دریافت",
  "alphabetAsc": "حروف الفبا (الف-ی)",
  "alphabetDesc": "حروف الفبا (ی-الف)",
  "highestDebt": "بیشترین بدهی",
  "highestCredit": "بیشترین طلب",
  "highestAmount": "بیشترین مبلغ",
  "lowestAmount": "کمترین مبلغ",
  "newest": "جدیدترین",
  "oldest": "قدیمی ترین",
  "orderBy": "ترتیب براساس",
  "sortByName": "مرتب‌سازی بر اساس نام",
  "sortByRecent": "مرتب‌سازی بر اساس آخرین فعالیت",
  "highestStock": "بیشترین موجودی",
  "search": {
    "persons": "جستجوی نام، شماره",
    "products": "جستجوی محصولات",
    "transactions": "جستجوی تراکنش‌ها، شخص"
  },
  "clearSearch": "پاک کردن جستجو",
  "addNewProduct": "افزودن محصول جدید",
  "editProduct": "ویرایش محصول",
  "editPerson": "ویرایش شخص",
  "addNewPerson": "افزودن شخص جدید",
  "saveProduct": "ذخیره محصول",
  "updatePerson": "به‌روزرسانی شخص",
  "updateProduct": "به‌روزرسانی محصول",
  "fieldRequired": "الزامی",
  "fieldOptional": "اختیاری",
  "units": "واحدها",
  "mainUnit": "واحد اصلی",
  "mainUnitHint": "مثال: کارتن، کیلو، بسته",
  "hasSecondaryUnit": "این محصول واحد فرعی دارد",
  "secondaryUnit": "واحد فرعی",
  "secondaryUnitHint": "مثال: عدد، گرام، بوتل",
  "unitRate": "نرخ واحد",
  "unitRateHint": "هر چند واحد فرعی برابر با یک واحد اصلی است را وارد کنید.",
  "stockUnit": "واحد موجودی",
  "categories": "دسته‌بندی‌ها",
  "manageCategories": "مدیریت دسته‌بندی‌ها",
  "searchCategories": "جستجوی دسته‌بندی‌ها",
  "noCategoriesFound": "دسته‌بندی‌ای پیدا نشد",
  "failedToLoadCategories": "بارگذاری دسته‌بندی‌ها ناموفق بود",
  "newCategory": "دسته‌بندی جدید",
  "categoryName": "نام دسته‌بندی",
  "categoryNameHint": "مثال: الکترونیک، لوازم اداری و غیره",
  "selectIcon": "انتخاب آیکن",
  "categoryColor": "رنگ دسته‌بندی",
  "createCategory": "ایجاد دسته‌بندی",
  "itemsCount": "{count} آیتم",
  "resultsCount": "{count} نتیجه",
  "initalStockQuantity": "موجودی اولیه",
  "initalStockHint": "تعداد را وارد کنید",
  "productName": "نام محصول",
  "productNameHint": "مثال: هدفون بی‌سیم پریمیوم",
  "productImage": "تصویر محصول",
  "tapToUploadOrCapturePhoto": "برای بارگذاری یا گرفتن عکس لمس کنید",
  "selectFile": "انتخاب فایل",
  "generalInformation": "اطلاعات عمومی",
  "skuOrBarcode": "کد کالا / بارکد",
  "skuOrBarcodeHint": "ورودی دستی یا اسکن",
  "category": "دسته‌بندی",
  "selectCategory": "انتخاب دسته‌بندی",
  "description": "توضیحات",
  "descriptionHint": "نمای کلی کوتاه از محصول...",
  "pricingAndTax": "قیمت و مالیات",
  "purchasePrice": "قیمت خرید",
  "sellingPrice": "قیمت فروش",
  "taxRate": "نرخ مالیات (%)",
  "taxRatePercent": "نرخ مالیات (%)",
  "taxRateHint": "مثال: 15",
  "inventorySettings": "تنظیمات انبار",
  "reorderLevel": "سطح سفارش مجدد (هشدار)",
  "lowStockThreshold": "آستانه کمبود موجودی",
  "warehouseLocation": "محل انبار / قفسه",
  "warehouseLocationHint": "مثال: انبار A، ردیف 4، قفسه 12",
  "electronics": "الکترونیک",
  "officeSupplies": "لوازم اداری",
  "homeAndLiving": "خانه و زندگی",
  "accessories": "لوازم جانبی",
  "product": "محصول",
  "person": "شخص",
  "name": "نام",
  "phone": "شماره تماس",
  "emailAddress": "ایمیل",
  "address": "آدرس",
  "customer": "خریدار",
  "customers": "خریداران",
  "supplier": "فروشنده",
  "suppliers": "فروشندگان",
  "both": "هردو",
  "owesYou": "به شما بدهکار",
  "youOwe": "شما بدهکارید",
  "openingBalance": "موجودی اولیه",
  "youPay": "شما پرداخت می‌کنید",
  "youReceive": "شما دریافت می‌کنید",
  "youPayNote": "شما باید به این شخص پول بپردازید",
  "youReceiveNote": "این شخص باید به شما پول بپردازد",
  "saving": "در حال ذخیره...",
  "nameRequired": "نام الزامی است",
  "invalidEmailAddress": "ایمیل معتبر وارد کنید",
  "invalidNumber": "عدد معتبر وارد کنید",
  "noPersonsFound": "شخصی پیدا نشد",
  "failedToLoadPersons": "بارگذاری اشخاص ناموفق بود",
  "noProductsFound": "محصولی پیدا نشد",
  "failedToLoadProducts": "بارگذاری محصولات ناموفق بود",
  "justNow": "همین حالا",
  "minutesAgo": "{count} دقیقه پیش",
  "hoursAgo": "{count} ساعت پیش",
  "yesterday": "دیروز",
  "daysAgo": "{count} روز پیش",
  "weeksAgo": "{count} هفته پیش",
  "monthsAgo": "{count} ماه پیش",
  "yearsAgo": "{count} سال پیش",
  "price": "قیمت",
  "stock": "موجودی",
  "inStock": "موجود",
  "lowStock": "موجودی کم",
  "outOfStock": "ناموجود",
  "image": "تصویر",
  "add": "افزودن",
  "cancel": "لغو",
  "delete": "حذف",
  "retry": "تلاش دوباره",
  "save": "ذخیره",
  "issue_date": "تاریخ صدور",
  "select_date": "انتخاب تاریخ",
  "due_date": "تاریخ سررسید",
  "optional": "اختیاری",
  "details": "جزئیات",
  "invoices": "فاکتورها",
  "invoicePayment": "پرداخت فاکتور",
  "manualEntry": "ثبت دستی",
  "linkedInvoice": "فاکتور مرتبط",
  "items": "آیتم‌ها",
  "summary": "خلاصه",
  "salesTrending": "روند فروش",
  "topClientsByRevenue": "برترین مشتریان بر اساس درآمد",
  "topItemsBySales": "برترین کالاها بر اساس فروش",
  "subtotal": "جمع کل",
  "quantity": "تعداد",
  "unit_price": "قیمت فی",
  "invoice_number": "شماره فاکتور",
  "select_product": "انتخاب کالا",
  "discount": "تخفیف",
  "tax": "مالیات",
  "total": "مجموع",
  "remaining": "باقی‌مانده",
  "collectionRate": "نرخ وصول",
  "collected": "وصول شده",
  "outstanding": "مانده",
  "avgInvoice": "میانگین فاکتور",
  "overdue": "معوق",
  "openBalance": "مانده باز",
  "moreDetails": "جزئیات بیشتر",
  "netCash": "خالص جریان نقدی",
  "paid": "تسویه شده",
  "unpaid": "تسویه نشده",
  "partialPaid": "نیمه تسویه شده",
  "amountExceedsTotal": "مبلغ از مجموع بیشتر است",
  "amountPaid": "مبلغ پرداخت شده",
  "saveInvoice": "ذخیره فاکتور",
  "updateInvoice": "به‌روزرسانی فاکتور",
  "editInvoice": "ویرایش فاکتور",
  "selectContact": "یک شخص را انتخاب کنید",
  "addAtLeastOneItem": "حداقل یک آیتم اضافه کنید",
  "invoiceSaved": "فاکتور با موفقیت ذخیره شد",
  "invoiceUpdated": "فاکتور با موفقیت به‌روزرسانی شد",
  "invoiceDeleted": "فاکتور با موفقیت حذف شد",
  "paymentSaved": "پرداخت با موفقیت ذخیره شد",
  "receiptSaved": "دریافت با موفقیت ذخیره شد",
  "fullPaidNow": "تسویه کامل الآن",
  "deleteInvoice": "حذف فاکتور",
  "deleteProductConfirmation": "محصول {name} حذف شود؟",
  "transactionsList": "لیست تراکنش‌ها",
  "showDetails": "نمایش جزئیات",
  "deletePersonConfirmation": "{name} حذف شود؟",
  "deleteInvoiceConfirmation": "این کار فاکتور را حذف می‌کند و در صورت امکان تغییرات موجودی آن را برمی‌گرداند.",
  "noInvoicesFound": "فاکتوری پیدا نشد",
  "failedToLoadInvoices": "بارگذاری فاکتورها ناموفق بود",
  "noPaymentsYet": "هنوز هیچ پرداختی اضافه نشده است",
  "noTransactionsFound": "تراکنشی پیدا نشد",
  "failedToLoadTransactions": "بارگذاری تراکنش‌ها ناموفق بود",
  "unknownContact": "شخص نامشخص",
  "appLock": "قفل برنامه",
  "secureWithBiometrics": "ایمن‌سازی برنامه با اثر انگشت یا تشخیص چهره",
  "languageAndFormat": "زبان و قالب",
  "currencyDateLanguage": "واحد پول، فرمت تاریخ، زبان",
  "customizeInvoice": "شخصی‌سازی فاکتور",
  "invoicePrefixExample": "پیشوند شماره فاکتور، مثل INV",
  "darkMode": "حالت تیره",
  "switchBetweenLightAndDark": "تغییر بین حالت روشن و تیره",
  "summaryOfSalesReports": "خلاصه گزارش‌های فروش",
  "exportInvoiceDataToExcel": "خروجی اطلاعات فاکتور به فایل اکسل",
  "editWithExcelOrGoogleSheet": "قابل ویرایش در اکسل یا گوگل شیت",
  "selectLanguage": "انتخاب زبان",
  "english": "English",
  "persian": "فارسی",
  "pashto": "پښتو",
  "comingSoon": "به‌زودی",
  "customRangeInvalid": "لطفاً بازه زمانی معتبر انتخاب کنید"
};
static const Map<String,dynamic> _ps = {
  "appName": "سودایس فایننس",
  "version": "نسخې",
  "dashboard": "داشبورد",
  "persons": "اشخاص",
  "inventory": "انبار",
  "transactions": "تراکنشونه",
  "finance": "مالیه",
  "settings": "تنظیمات",
  "reports": "راپورونه",
  "currentPosition": "اوسنی حالت",
  "cashOnHand": "نغدي موجودي",
  "inventoryValue": "د موجودۍ ارزښت",
  "potentialRevenue": "احتمالي عاید",
  "invoiceStatus": "د بلونو حالت",
  "topSellingProducts": "ډېر پلورل شوي توکي",
  "noReportData": "د ټاکلې مودې لپاره معلومات نشته",
  "noRecentActivity": "وروستی فعالیت نشته",
  "noInventoryAlerts": "د موجودۍ خبرتیا نشته",
  "failedToLoadReports": "د راپورونو پورته کول ناکام شول",
  "totalBalance": "ټولی موجودی",
  "balance": "موجودی",
  "amount": "مقدار",
  "filter": "فیلټر",
  "day": "ورځ",
  "week": "اونۍ",
  "month": "میاشت",
  "year": "کال",
  "customTime": "د وخت انتخاب",
  "last30Days": "وروستي ۳۰ ورځې",
  "thisMonth": "دا میاشت",
  "lastMonth": "تېره میاشت",
  "thisQuarter": "دا ربع",
  "thisYear": "دا کال",
  "lastYear": "تېر کال",
  "customRange": "ځانګړې موده",
  "startDate": "د پیل نېټه",
  "endDate": "د پای نېټه",
  "apply": "پلي کول",
  "currentStock": "اوسنی موجودی",
  "totalReceivables": "ټول پورونه",
  "toCollect": "د اخیستلو لپاره",
  "toPay": "د ورکړې لپاره",
  "all": "همه",
  "sale": "فروش",
  "purchase": "خرید",
  "payment": "پرداخت",
  "returned": "بازگشتی",
  "receipt": "دریافت",
  "recentActivities": "فعالیت های اخیر",
  "recentlyActive": "وروستي فعال",
  "sold_to": "فروش {product} به {person}",
  "bought_from": "خرید {product} از {person}",
  "paid_to": "پرداخت {amount} به {person}",
  "received_from": "دریافت {amount} از {person}",
  "addNewSale": "فروش جدید",
  "addNewPurchase": "خرید جدید",
  "addNewPayment": "پرداخت جدید",
  "addNewReceipt": "نوی دریافت",
  "addPayment": "تادیه اضافه کړئ",
  "savePayment": "د تادیې خوندي کول",
  "saveReceipt": "د ترلاسه کولو خوندي کول",
  "newSale": "نوی فروش",
  "newPurchase": "نوی خرید",
  "receive": "ترلاسه کول",
  "newExpense": "نوی لګښت",
  "trade": "سوداګري",
  "cashFlow": "نغدي جریان",
  "management": "مدیریت",
  "internalTransfer": "داخلي انتقال",
  "recordBusinessCosts": "د سوداګرۍ لګښتونه ثبت کړئ",
  "moveFundsBetweenAccounts": "د حسابونو ترمنځ پیسې انتقال کړئ",
  "lastActive": "آخرین فعالیت",
  "net": "خالص",
  "netBalance": "خالص بیلانس",
  "lastPayment": "آخرین پرداخت",
  "lastReceipt": "آخرین دریافت",
  "alphabetAsc": "حروف الفبا (الف-ی)",
  "alphabetDesc": "حروف الفبا (ی-الف)",
  "highestDebt": "بیشترین بدهی",
  "highestCredit": "بیشترین طلب",
  "highestAmount": "لوړه اندازه",
  "lowestAmount": "ټیټه اندازه",
  "newest": "جدیدترین",
  "oldest": "قدیمی ترین",
  "orderBy": "ترتیب براساس",
  "sortByName": "د نوم له مخې ترتیب",
  "sortByRecent": "د وروستي فعالیت له مخې ترتیب",
  "highestStock": "بیشترین موجودی",
  "search": {
    "persons": "Search name, phone",
    "products": "Search products",
    "transactions": "تراکنشونه او شخص ولټوئ"
  },
  "clearSearch": "لټون پاک کړئ",
  "addNewProduct": "افزودن محصول جدید",
  "editPerson": "د شخص سمون",
  "addNewPerson": "افزودن شخص جدید",
  "updatePerson": "د شخص تازه کول",
  "units": "واحدونه",
  "mainUnit": "اصلي واحد",
  "mainUnitHint": "لکه کارتن، کیلو، بکس",
  "hasSecondaryUnit": "دا محصول فرعي واحد لري",
  "secondaryUnit": "فرعي واحد",
  "secondaryUnitHint": "لکه دانه، ګرام، بوتل",
  "unitRate": "د واحد نسبت",
  "unitRateHint": "وارد کنید که هر چند واحد فرعی برابر با یک واحد اصلی است.",
  "stockUnit": "د موجودۍ واحد",
  "initalStockQuantity": "موجودی اولیه",
  "productName": "نام محصول",
  "product": "محصول",
  "person": "شخص",
  "name": "نام",
  "phone": "شمېره",
  "emailAddress": "برېښنالیک",
  "address": "پته",
  "customer": "پېرودونکی",
  "customers": "پېرودونکي",
  "supplier": "عرضه کوونکی",
  "suppliers": "عرضه کوونکي",
  "both": "دواړه",
  "owesYou": "تاسو ته پوروړی",
  "youOwe": "تاسو پوروړي یاست",
  "openingBalance": "لومړنی بیلانس",
  "youPay": "تاسو ورکوئ",
  "youReceive": "تاسو ترلاسه کوئ",
  "youPayNote": "تاسو باید دې شخص ته پیسې ورکړئ.",
  "youReceiveNote": "دا شخص باید تاسو ته پیسې درکړي.",
  "saving": "خوندي کېږي...",
  "nameRequired": "نوم اړین دی",
  "invalidEmailAddress": "سم برېښنالیک ولیکئ",
  "invalidNumber": "سمه شمېره ولیکئ",
  "noPersonsFound": "هیڅ شخص ونه موندل شو",
  "failedToLoadPersons": "د اشخاصو پورته کول ناکام شول",
  "justNow": "همدا اوس",
  "minutesAgo": "{count} دقیقې مخکې",
  "hoursAgo": "{count} ساعته مخکې",
  "yesterday": "پرون",
  "daysAgo": "{count} ورځې مخکې",
  "weeksAgo": "{count} اونۍ مخکې",
  "monthsAgo": "{count} میاشتې مخکې",
  "yearsAgo": "{count} کاله مخکې",
  "price": "قیمت",
  "stock": "موجودی",
  "inStock": "په موجودي کې",
  "image": "تصویر",
  "add": "افزودن",
  "cancel": "لغو",
  "delete": "حذف",
  "retry": "بیا هڅه وکړئ",
  "save": "ذخیره",
  "issue_date": "تاریخ صدور",
  "select_date": "انتخاب تاریخ",
  "due_date": "تاریخ سررسید",
  "optional": "اختیاری",
  "details": "جزئیات",
  "invoices": "فاکتورونه",
  "invoicePayment": "د فاکتور تادیه",
  "manualEntry": "لاسي ثبت",
  "linkedInvoice": "اړوند فاکتور",
  "items": "آیتم‌ها",
  "summary": "خلاصه",
  "salesTrending": "د پلور بهیر",
  "topClientsByRevenue": "د عاید له مخې غوره پېرودونکي",
  "topItemsBySales": "د پلور له مخې غوره توکي",
  "subtotal": "جمع کل",
  "quantity": "تعداد",
  "unit_price": "قیمت فی",
  "invoice_number": "شماره فاکتور",
  "select_product": "انتخاب کالا",
  "discount": "تخفیف",
  "tax": "مالیه",
  "total": "ټول",
  "remaining": "پاتې",
  "collectionRate": "د راټولولو کچه",
  "collected": "ترلاسه شوي",
  "outstanding": "پاتې",
  "avgInvoice": "د بل منځنۍ کچه",
  "overdue": "ځنډني",
  "openBalance": "پرانیستی بیلانس",
  "moreDetails": "نور جزئیات",
  "netCash": "خالص نغدي",
  "paid": "تسویه شده",
  "unpaid": "تسویه نشده",
  "partialPaid": "نیمه تسویه شده",
  "amountExceedsTotal": "مبلغ از مجموع بیشتر است",
  "amountPaid": "مبلغ پرداخت شده",
  "saveInvoice": "د فاکتور ذخیره",
  "updateInvoice": "فاکتور تازه کول",
  "editInvoice": "فاکتور سمول",
  "selectContact": "یو شخص وټاکئ",
  "addAtLeastOneItem": "لږ تر لږه یو توکی اضافه کړئ",
  "invoiceSaved": "فاکتور په بریالیتوب سره خوندي شو",
  "invoiceUpdated": "فاکتور په بریالیتوب سره تازه شو",
  "invoiceDeleted": "فاکتور په بریالیتوب سره حذف شو",
  "paymentSaved": "تادیه په بریالیتوب سره خوندي شوه",
  "receiptSaved": "ترلاسه کول په بریالیتوب سره خوندي شول",
  "fullPaidNow": "اوس بشپړ تسویه",
  "deleteInvoice": "د فاکتور حذف",
  "deleteProductConfirmation": "محصول {name} حذف شي؟",
  "transactionsList": "د تراکنشونو لست",
  "showDetails": "جزئیات ښکاره کړئ",
  "deletePersonConfirmation": "{name} حذف شي؟",
  "deleteInvoiceConfirmation": "دا به فاکتور حذف کړي او که ممکنه وي د هغه د موجودي بدلونونه به بېرته وګرځوي.",
  "noInvoicesFound": "هیڅ فاکتور ونه موندل شو",
  "failedToLoadInvoices": "د فاکتورونو پورته کول ناکام شول",
  "noPaymentsYet": "لا تراوسه هېڅ تادیه نه ده اضافه شوې",
  "noTransactionsFound": "هیڅ تراکنش ونه موندل شو",
  "failedToLoadTransactions": "د تراکنشونو پورته کول ناکام شول",
  "unknownContact": "نامعلوم شخص",
  "appLock": "د اپ قفل",
  "secureWithBiometrics": "اپ د ګوتې نښې یا مخ پېژندنې سره خوندي کړئ",
  "languageAndFormat": "ژبه او بڼه",
  "currencyDateLanguage": "اسعار، د نېټې بڼه، ژبه",
  "customizeInvoice": "بل تنظیمول",
  "invoicePrefixExample": "د بل مخکینی لکه INV",
  "darkMode": "تیاره بڼه",
  "switchBetweenLightAndDark": "د روښانه او تیاره بڼې ترمنځ بدلول",
  "summaryOfSalesReports": "د پلور راپورونو لنډیز",
  "exportInvoiceDataToExcel": "د بل معلومات اکسل ته صادر کړئ",
  "editWithExcelOrGoogleSheet": "په اکسل یا ګوګل شیټ کې یې سمولای شئ",
  "selectLanguage": "ژبه وټاکئ",
  "english": "English",
  "persian": "فارسی",
  "pashto": "پښتو",
  "comingSoon": "ژر راځي",
  "customRangeInvalid": "مهرباني وکړئ سمه نېټه وټاکئ"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": _en, "fa": _fa, "ps": _ps};
}
