// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> _en = {
    "appName": "Sodais Finance",
    "version": "Version",
    "dashboard": "Dashboard",
    "persons": "Persons",
    "inventory": "Inventory",
    "finance": "Finance",
    "reports": "Reports",
    "totalBalance": "Total Balance",
    "balance": "Balance",
    "amount": "Amount",
    "filter": "Filter",
    "day": "Day",
    "week": "Week",
    "month": "Month",
    "year": "Year",
    "customTime": "Custom Time",
    "totalReceivables": "Total Receivables",
    "currentStock": "Current Stock",
    "all": "All",
    "sale": "Sale",
    "purchase": "Purchase",
    "payment": "Payment",
    "receipt": "receipt",
    "recentActivities": "Recent Activities",
    "sold_to": "Sold {product} to {person}",
    "bought_from": "Bought {product} from {person}",
    "paid_to": "Paid {amount} to {person}",
    "received_from": "Received {amount} from {person}",
    "addNewSale": "Add New Sale",
    "addNewPurchase": "Add New Purchase",
    "addNewPayment": "Add New Payment",
    "addNewReceipt": "Add New Receipt",
    "credit": "Credit",
    "debt": "Debt",
    "settled": "Settle",
    "lastActive": "Last Active",
    "lastPayment": "Last Payment",
    "lastReceipt": "Last Receipt",
    "alphabetAsc": "alphabet A-Z",
    "alphabetDesc": "alphabet Z-A",
    "highestDebt": "Highest Debt",
    "highestCredit": "Highest Credit",
    "newest": "Newest",
    "oldest": "Oldest",
    "orderBy": "Order By",
    "highestStock": "Highest Stock",
    "search": {"persons": "Search name, phone", "products": "Search products"},
    "addNewProduct": "Add New Product",
    "addNewPerson": "Add New Person",
    "initalStockQuantity": "Initial Stock Quantity",
    "productName": "Product Name",
    "product": "Product",
    "person": "Person",
    "name": "Name",
    "phone": "Phone",
    "emailAddress": "Email Address",
    "address": "Address",
    "customer": "Customer",
    "supplier": "Supplier",
    "both": "Both",
    "openingBalance": "Opening Balance",
    "youPay": "You Pay",
    "youReceive": "You Receive",
    "youPayNote": "This person should pay you money.",
    "youReceiveNote": "You should pay this person money.",
    "saving": "Saving...",
    "nameRequired": "Name is required",
    "invalidEmailAddress": "Enter a valid email address",
    "invalidNumber": "Enter a valid number",
    "price": "Price",
    "stock": "Stock",
    "image": "Image",
    "add": "Add",
    "cancel": "Cancel",
    "save": "Save",
  };
  static const Map<String, dynamic> _fa = {
    "appName": "مدیریت فروشگاه",
    "version": "نسخه",
    "dashboard": "داشبورد",
    "persons": "اشخاص",
    "inventory": "انبار",
    "finance": "امور مالی",
    "reports": "گزارشات",
    "totalBalance": "موجودی کل",
    "balance": "موجودی",
    "amount": "مقدار",
    "filter": "فیلتر",
    "day": "روز",
    "week": "هفته",
    "month": "ماه",
    "year": "سال",
    "customTime": "انتخاب زمان",
    "totalReceivables": "مانده حساب ها",
    "currentStock": "موجودی فعلی",
    "all": "همه",
    "sale": "فروش",
    "purchase": "خرید",
    "payment": "پرداخت",
    "receipt": "دریافت",
    "recentActivities": "فعالیت های اخیر",
    "sold_to": "فروش {product} به {person}",
    "bought_from": "خرید {product} از {person}",
    "paid_to": "پرداخت {amount} به {person}",
    "received_from": "دریافت {amount} از {person}",
    "addNewSale": "فروش جدید",
    "addNewPurchase": "خرید جدید",
    "addNewPayment": "پرداخت جدید",
    "credit": "طلب",
    "debt": "بدهی",
    "settled": "تسویه شده",
    "lastActive": "آخرین فعالیت",
    "lastPayment": "آخرین پرداخت",
    "lastReceipt": "آخرین دریافت",
    "alphabetAsc": "حروف الفبا (الف-ی)",
    "alphabetDesc": "حروف الفبا (ی-الف)",
    "highestDebt": "بیشترین بدهی",
    "highestCredit": "بیشترین طلب",
    "newest": "جدیدترین",
    "oldest": "قدیمی ترین",
    "orderBy": "ترتیب براساس",
    "highestStock": "بیشترین موجودی",
    "search": {"persons": "جستجوی نام، شماره", "products": "جستجوی محصولات"},
    "addNewProduct": "افزودن محصول جدید",
    "addNewPerson": "افزودن شخص جدید",
    "initalStockQuantity": "موجودی اولیه",
    "productName": "نام محصول",
    "product": "محصول",
    "person": "شخص",
    "name": "نام",
    "phone": "شماره تماس",
    "emailAddress": "ایمیل",
    "address": "آدرس",
    "customer": "خریدار",
    "supplier": "فروشنده",
    "both": "هردو",
    "openingBalance": "موجودی اولیه",
    "youPay": "بدهکار",
    "youReceive": "بستانکار",
    "youPayNote": "باید به شما پولی بپردازد",
    "youReceiveNote": "بستانکار (طلب کار): باید پولی به آن بپردازید",
    "saving": "در حال ذخیره...",
    "nameRequired": "نام الزامی است",
    "invalidEmailAddress": "ایمیل معتبر وارد کنید",
    "invalidNumber": "عدد معتبر وارد کنید",
    "price": "قیمت",
    "stock": "موجودی",
    "image": "تصویر",
    "add": "افزودن",
    "cancel": "لغو",
    "save": "ذخیره",
  };
  static const Map<String, dynamic> _ps = {
    "appName": "",
    "version": "نسخې",
    "dashboard": "داشبورد",
    "persons": "اشخاص",
    "inventory": "انبار",
    "finance": "مالیه",
    "reports": "Reports",
    "totalBalance": "ټولی موجودی",
    "balance": "موجودی",
    "amount": "مقدار",
    "filter": "فیلټر",
    "day": "ورځ",
    "week": "اونۍ",
    "month": "میاشت",
    "year": "کال",
    "customTime": "د وخت انتخاب",
    "currentStock": "اوسنی موجودی",
    "totalReceivables": "ټول پورونه",
    "all": "همه",
    "sale": "فروش",
    "purchase": "خرید",
    "payment": "پرداخت",
    "receipt": "دریافت",
    "recentActivities": "فعالیت های اخیر",
    "sold_to": "فروش {product} به {person}",
    "bought_from": "خرید {product} از {person}",
    "paid_to": "پرداخت {amount} به {person}",
    "received_from": "دریافت {amount} از {person}",
    "addNewSale": "فروش جدید",
    "addNewPurchase": "خرید جدید",
    "addNewPayment": "پرداخت جدید",
    "lastActive": "آخرین فعالیت",
    "lastPayment": "آخرین پرداخت",
    "lastReceipt": "آخرین دریافت",
    "alphabetAsc": "حروف الفبا (الف-ی)",
    "alphabetDesc": "حروف الفبا (ی-الف)",
    "highestDebt": "بیشترین بدهی",
    "highestCredit": "بیشترین طلب",
    "newest": "جدیدترین",
    "oldest": "قدیمی ترین",
    "orderBy": "ترتیب براساس",
    "highestStock": "بیشترین موجودی",
    "search": {"persons": "Search name, phone", "products": "Search products"},
    "addNewProduct": "افزودن محصول جدید",
    "addNewPerson": "افزودن شخص جدید",
    "initalStockQuantity": "موجودی اولیه",
    "productName": "نام محصول",
    "product": "محصول",
    "person": "شخص",
    "name": "نام",
    "phone": "شمېره",
    "emailAddress": "برېښنالیک",
    "address": "پته",
    "customer": "پېرودونکی",
    "supplier": "عرضه کوونکی",
    "both": "دواړه",
    "openingBalance": "لومړنی بیلانس",
    "youPay": "تاسو ورکوئ",
    "youReceive": "تاسو ترلاسه کوئ",
    "youPayNote": "باید تاسو ته پیسې درکړي.",
    "youReceiveNote": "تاسو باید دې شخص ته پیسې ورکړئ.",
    "saving": "خوندي کېږي...",
    "nameRequired": "نوم اړین دی",
    "invalidEmailAddress": "سم برېښنالیک ولیکئ",
    "invalidNumber": "سمه شمېره ولیکئ",
    "price": "قیمت",
    "stock": "موجودی",
    "image": "تصویر",
    "add": "افزودن",
    "cancel": "لغو",
    "save": "ذخیره",
  };
  static const Map<String, Map<String, dynamic>> mapLocales = {
    "en": _en,
    "fa": _fa,
    "ps": _ps,
  };
}
