// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _en = {
  "appName": "Sodais Finance",
  "version": "Version",
  "dashboard": "Dashboard",
  "persons": "Persons",
  "inventory": "Inventory",
  "finance": "Finance",
  "reports": "Reports",
  "totalBalance": "Total Balance",
  "balance": "Balance",
  "amount": "Amount",
  "filter": "Filter",
  "day": "Day",
  "week": "Week",
  "month": "Month",
  "year": "Year",
  "customTime": "Custom Time",
  "totalReceivables": "Total Receivables",
  "toCollect": "To Collect",
  "toPay": "To Pay",
  "currentStock": "Current Stock",
  "all": "All",
  "sale": "Sale",
  "purchase": "Purchase",
  "payment": "Payment",
  "receipt": "receipt",
  "recentActivities": "Recent Activities",
  "recentlyActive": "Recently Active",
  "sold_to": "Sold {product} to {person}",
  "bought_from": "Bought {product} from {person}",
  "paid_to": "Paid {amount} to {person}",
  "received_from": "Received {amount} from {person}",
  "addNewSale": "Add New Sale",
  "addNewPurchase": "Add New Purchase",
  "addNewPayment": "Add New Payment",
  "addNewReceipt": "Add New Receipt",
  "credit": "Credit",
  "debt": "Debt",
  "settled": "Settle",
  "net": "Net",
  "netBalance": "Net Balance",
  "lastActive": "Last Active",
  "lastPayment": "Last Payment",
  "lastReceipt": "Last Receipt",
  "alphabetAsc": "alphabet A-Z",
  "alphabetDesc": "alphabet Z-A",
  "highestDebt": "Highest Debt",
  "highestCredit": "Highest Credit",
  "newest": "Newest",
  "oldest": "Oldest",
  "orderBy": "Order By",
  "sortByName": "Sort by Name",
  "sortByRecent": "Sort by Recent",
  "highestStock": "Highest Stock",
  "search": {
    "persons": "Search name, phone",
    "products": "Search products"
  },
  "clearSearch": "Clear Search",
  "addNewProduct": "Add New Product",
  "editProduct": "Edit Product",
  "addNewPerson": "Add New Person",
  "saveProduct": "Save Product",
  "updateProduct": "Update Product",
  "fieldRequired": "Required",
  "fieldOptional": "Optional",
  "categories": "Categories",
  "manageCategories": "Manage categories",
  "searchCategories": "Search categories",
  "noCategoriesFound": "No categories found",
  "failedToLoadCategories": "Failed to load categories",
  "newCategory": "New Category",
  "categoryName": "Category Name",
  "categoryNameHint": "Example: Electronics, Office Supplies, etc.",
  "selectIcon": "Select Icon",
  "categoryColor": "Category Color",
  "createCategory": "Create Category",
  "itemsCount": "{count} Items",
  "resultsCount": "{count} results",
  "initalStockQuantity": "Initial Stock Quantity",
  "initalStockHint": "Enter quantity",
  "productName": "Product Name",
  "productNameHint": "e.g. Premium Wireless Headphones",
  "productImage": "Product Image",
  "tapToUploadOrCapturePhoto": "Tap to upload or capture photo",
  "selectFile": "Select File",
  "generalInformation": "General Information",
  "skuOrBarcode": "SKU / Barcode",
  "skuOrBarcodeHint": "Manual entry or scan",
  "category": "Category",
  "selectCategory": "Select category",
  "description": "Description",
  "descriptionHint": "Brief product overview...",
  "pricingAndTax": "Pricing & Tax",
  "purchasePrice": "Purchase Price",
  "sellingPrice": "Selling Price",
  "taxRate": "Tax Rate (%)",
  "taxRatePercent": "Tax Rate (%)",
  "taxRateHint": "e.g. 15",
  "inventorySettings": "Inventory Settings",
  "reorderLevel": "Reorder Level (Alert)",
  "lowStockThreshold": "Low stock threshold",
  "warehouseLocation": "Warehouse / Rack Location",
  "warehouseLocationHint": "e.g. Warehouse A, Row 4, Shelf 12",
  "electronics": "Electronics",
  "officeSupplies": "Office Supplies",
  "homeAndLiving": "Home & Living",
  "accessories": "Accessories",
  "product": "Product",
  "person": "Person",
  "name": "Name",
  "phone": "Phone",
  "emailAddress": "Email Address",
  "address": "Address",
  "customer": "Customer",
  "customers": "Customers",
  "supplier": "Supplier",
  "suppliers": "Suppliers",
  "both": "Both",
  "owesYou": "Owes You",
  "youOwe": "You Owe",
  "openingBalance": "Opening Balance",
  "youPay": "You Pay",
  "youReceive": "You Receive",
  "youPayNote": "This person should pay you money.",
  "youReceiveNote": "You should pay this person money.",
  "saving": "Saving...",
  "nameRequired": "Name is required",
  "invalidEmailAddress": "Enter a valid email address",
  "invalidNumber": "Enter a valid number",
  "noPersonsFound": "No persons found",
  "failedToLoadPersons": "Failed to load persons",
  "noProductsFound": "No products found",
  "failedToLoadProducts": "Failed to load products",
  "justNow": "Just now",
  "minutesAgo": "{count}m ago",
  "hoursAgo": "{count}h ago",
  "yesterday": "Yesterday",
  "daysAgo": "{count}d ago",
  "weeksAgo": "{count}w ago",
  "monthsAgo": "{count}mo ago",
  "yearsAgo": "{count}y ago",
  "price": "Price",
  "stock": "Stock",
  "lowStock": "Low Stock",
  "outOfStock": "Out of Stock",
  "image": "Image",
  "add": "Add",
  "cancel": "Cancel",
  "save": "Save"
};
static const Map<String,dynamic> _fa = {
  "appName": "مدیریت فروشگاه",
  "version": "نسخه",
  "dashboard": "داشبورد",
  "persons": "اشخاص",
  "inventory": "انبار",
  "finance": "امور مالی",
  "reports": "گزارشات",
  "totalBalance": "موجودی کل",
  "balance": "موجودی",
  "amount": "مقدار",
  "filter": "فیلتر",
  "day": "روز",
  "week": "هفته",
  "month": "ماه",
  "year": "سال",
  "customTime": "انتخاب زمان",
  "totalReceivables": "مانده حساب ها",
  "toCollect": "دریافتنی",
  "toPay": "پرداختنی",
  "currentStock": "موجودی فعلی",
  "all": "همه",
  "sale": "فروش",
  "purchase": "خرید",
  "payment": "پرداخت",
  "receipt": "دریافت",
  "recentActivities": "فعالیت های اخیر",
  "recentlyActive": "اخیراً فعال",
  "sold_to": "فروش {product} به {person}",
  "bought_from": "خرید {product} از {person}",
  "paid_to": "پرداخت {amount} به {person}",
  "received_from": "دریافت {amount} از {person}",
  "addNewSale": "فروش جدید",
  "addNewPurchase": "خرید جدید",
  "addNewPayment": "پرداخت جدید",
  "credit": "طلب",
  "debt": "بدهی",
  "settled": "تسویه شده",
  "net": "خالص",
  "netBalance": "مانده خالص",
  "lastActive": "آخرین فعالیت",
  "lastPayment": "آخرین پرداخت",
  "lastReceipt": "آخرین دریافت",
  "alphabetAsc": "حروف الفبا (الف-ی)",
  "alphabetDesc": "حروف الفبا (ی-الف)",
  "highestDebt": "بیشترین بدهی",
  "highestCredit": "بیشترین طلب",
  "newest": "جدیدترین",
  "oldest": "قدیمی ترین",
  "orderBy": "ترتیب براساس",
  "sortByName": "مرتب‌سازی بر اساس نام",
  "sortByRecent": "مرتب‌سازی بر اساس آخرین فعالیت",
  "highestStock": "بیشترین موجودی",
  "search": {
    "persons": "جستجوی نام، شماره",
    "products": "جستجوی محصولات"
  },
  "clearSearch": "پاک کردن جستجو",
  "addNewProduct": "افزودن محصول جدید",
  "editProduct": "ویرایش محصول",
  "addNewPerson": "افزودن شخص جدید",
  "saveProduct": "ذخیره محصول",
  "updateProduct": "به‌روزرسانی محصول",
  "fieldRequired": "الزامی",
  "fieldOptional": "اختیاری",
  "categories": "دسته‌بندی‌ها",
  "manageCategories": "مدیریت دسته‌بندی‌ها",
  "searchCategories": "جستجوی دسته‌بندی‌ها",
  "noCategoriesFound": "دسته‌بندی‌ای پیدا نشد",
  "failedToLoadCategories": "بارگذاری دسته‌بندی‌ها ناموفق بود",
  "newCategory": "دسته‌بندی جدید",
  "categoryName": "نام دسته‌بندی",
  "categoryNameHint": "مثال: الکترونیک، لوازم اداری و غیره",
  "selectIcon": "انتخاب آیکن",
  "categoryColor": "رنگ دسته‌بندی",
  "createCategory": "ایجاد دسته‌بندی",
  "itemsCount": "{count} آیتم",
  "resultsCount": "{count} نتیجه",
  "initalStockQuantity": "موجودی اولیه",
  "initalStockHint": "تعداد را وارد کنید",
  "productName": "نام محصول",
  "productNameHint": "مثال: هدفون بی‌سیم پریمیوم",
  "productImage": "تصویر محصول",
  "tapToUploadOrCapturePhoto": "برای بارگذاری یا گرفتن عکس لمس کنید",
  "selectFile": "انتخاب فایل",
  "generalInformation": "اطلاعات عمومی",
  "skuOrBarcode": "کد کالا / بارکد",
  "skuOrBarcodeHint": "ورودی دستی یا اسکن",
  "category": "دسته‌بندی",
  "selectCategory": "انتخاب دسته‌بندی",
  "description": "توضیحات",
  "descriptionHint": "نمای کلی کوتاه از محصول...",
  "pricingAndTax": "قیمت و مالیات",
  "purchasePrice": "قیمت خرید",
  "sellingPrice": "قیمت فروش",
  "taxRate": "نرخ مالیات (%)",
  "taxRatePercent": "نرخ مالیات (%)",
  "taxRateHint": "مثال: 15",
  "inventorySettings": "تنظیمات انبار",
  "reorderLevel": "سطح سفارش مجدد (هشدار)",
  "lowStockThreshold": "آستانه کمبود موجودی",
  "warehouseLocation": "محل انبار / قفسه",
  "warehouseLocationHint": "مثال: انبار A، ردیف 4، قفسه 12",
  "electronics": "الکترونیک",
  "officeSupplies": "لوازم اداری",
  "homeAndLiving": "خانه و زندگی",
  "accessories": "لوازم جانبی",
  "product": "محصول",
  "person": "شخص",
  "name": "نام",
  "phone": "شماره تماس",
  "emailAddress": "ایمیل",
  "address": "آدرس",
  "customer": "خریدار",
  "customers": "خریداران",
  "supplier": "فروشنده",
  "suppliers": "فروشندگان",
  "both": "هردو",
  "owesYou": "به شما بدهکار",
  "youOwe": "شما بدهکارید",
  "openingBalance": "موجودی اولیه",
  "youPay": "بدهکار",
  "youReceive": "بستانکار",
  "youPayNote": "باید به شما پولی بپردازد",
  "youReceiveNote": "بستانکار (طلب کار): باید پولی به آن بپردازید",
  "saving": "در حال ذخیره...",
  "nameRequired": "نام الزامی است",
  "invalidEmailAddress": "ایمیل معتبر وارد کنید",
  "invalidNumber": "عدد معتبر وارد کنید",
  "noPersonsFound": "شخصی پیدا نشد",
  "failedToLoadPersons": "بارگذاری اشخاص ناموفق بود",
  "noProductsFound": "محصولی پیدا نشد",
  "failedToLoadProducts": "بارگذاری محصولات ناموفق بود",
  "justNow": "همین حالا",
  "minutesAgo": "{count} دقیقه پیش",
  "hoursAgo": "{count} ساعت پیش",
  "yesterday": "دیروز",
  "daysAgo": "{count} روز پیش",
  "weeksAgo": "{count} هفته پیش",
  "monthsAgo": "{count} ماه پیش",
  "yearsAgo": "{count} سال پیش",
  "price": "قیمت",
  "stock": "موجودی",
  "lowStock": "موجودی کم",
  "outOfStock": "ناموجود",
  "image": "تصویر",
  "add": "افزودن",
  "cancel": "لغو",
  "save": "ذخیره"
};
static const Map<String,dynamic> _ps = {
  "appName": "",
  "version": "نسخې",
  "dashboard": "داشبورد",
  "persons": "اشخاص",
  "inventory": "انبار",
  "finance": "مالیه",
  "reports": "Reports",
  "totalBalance": "ټولی موجودی",
  "balance": "موجودی",
  "amount": "مقدار",
  "filter": "فیلټر",
  "day": "ورځ",
  "week": "اونۍ",
  "month": "میاشت",
  "year": "کال",
  "customTime": "د وخت انتخاب",
  "currentStock": "اوسنی موجودی",
  "totalReceivables": "ټول پورونه",
  "toCollect": "د اخیستلو لپاره",
  "toPay": "د ورکړې لپاره",
  "all": "همه",
  "sale": "فروش",
  "purchase": "خرید",
  "payment": "پرداخت",
  "receipt": "دریافت",
  "recentActivities": "فعالیت های اخیر",
  "recentlyActive": "وروستي فعال",
  "sold_to": "فروش {product} به {person}",
  "bought_from": "خرید {product} از {person}",
  "paid_to": "پرداخت {amount} به {person}",
  "received_from": "دریافت {amount} از {person}",
  "addNewSale": "فروش جدید",
  "addNewPurchase": "خرید جدید",
  "addNewPayment": "پرداخت جدید",
  "lastActive": "آخرین فعالیت",
  "net": "خالص",
  "netBalance": "خالص بیلانس",
  "lastPayment": "آخرین پرداخت",
  "lastReceipt": "آخرین دریافت",
  "alphabetAsc": "حروف الفبا (الف-ی)",
  "alphabetDesc": "حروف الفبا (ی-الف)",
  "highestDebt": "بیشترین بدهی",
  "highestCredit": "بیشترین طلب",
  "newest": "جدیدترین",
  "oldest": "قدیمی ترین",
  "orderBy": "ترتیب براساس",
  "sortByName": "د نوم له مخې ترتیب",
  "sortByRecent": "د وروستي فعالیت له مخې ترتیب",
  "highestStock": "بیشترین موجودی",
  "search": {
    "persons": "Search name, phone",
    "products": "Search products"
  },
  "clearSearch": "لټون پاک کړئ",
  "addNewProduct": "افزودن محصول جدید",
  "addNewPerson": "افزودن شخص جدید",
  "initalStockQuantity": "موجودی اولیه",
  "productName": "نام محصول",
  "product": "محصول",
  "person": "شخص",
  "name": "نام",
  "phone": "شمېره",
  "emailAddress": "برېښنالیک",
  "address": "پته",
  "customer": "پېرودونکی",
  "customers": "پېرودونکي",
  "supplier": "عرضه کوونکی",
  "suppliers": "عرضه کوونکي",
  "both": "دواړه",
  "owesYou": "تاسو ته پوروړی",
  "youOwe": "تاسو پوروړي یاست",
  "openingBalance": "لومړنی بیلانس",
  "youPay": "تاسو ورکوئ",
  "youReceive": "تاسو ترلاسه کوئ",
  "youPayNote": "باید تاسو ته پیسې درکړي.",
  "youReceiveNote": "تاسو باید دې شخص ته پیسې ورکړئ.",
  "saving": "خوندي کېږي...",
  "nameRequired": "نوم اړین دی",
  "invalidEmailAddress": "سم برېښنالیک ولیکئ",
  "invalidNumber": "سمه شمېره ولیکئ",
  "noPersonsFound": "هیڅ شخص ونه موندل شو",
  "failedToLoadPersons": "د اشخاصو پورته کول ناکام شول",
  "justNow": "همدا اوس",
  "minutesAgo": "{count} دقیقې مخکې",
  "hoursAgo": "{count} ساعته مخکې",
  "yesterday": "پرون",
  "daysAgo": "{count} ورځې مخکې",
  "weeksAgo": "{count} اونۍ مخکې",
  "monthsAgo": "{count} میاشتې مخکې",
  "yearsAgo": "{count} کاله مخکې",
  "price": "قیمت",
  "stock": "موجودی",
  "image": "تصویر",
  "add": "افزودن",
  "cancel": "لغو",
  "save": "ذخیره"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": _en, "fa": _fa, "ps": _ps};
}
